name: "OpenClaw (Moltbot)"
description: "A personal AI assistant you run on your own devices. Connects to WhatsApp, Telegram, Discord, Slack, and 50+ other services with persistent memory and extensible capabilities."
url: "https://openclaw.ai/"
docs: "https://docs.openclaw.ai/providers/openrouter"
tags:
  - productivity
open_source: "https://github.com/openclaw/openclaw"
date_added: "2026-01-27"
